# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  api:
    build:
      context: .
      dockerfile: DockerfileApi
    restart: always
    image: api
    ports:
      - 5000:80

  httpclientefcore:
    image: httpclientefcore
    build:
      context: .
      dockerfile: DockerfileHttp
  proxy:
    image: nginx
    ports:
      - 80:80
    volumes:
      - .\default.conf:/etc/nginx/conf.d/default.conf:ro
  
